name: Build and Deploy

on:
  push:
    branches: [development, main]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER_DEV: nmrxiv-dev
  GKE_CLUSTER_PROD: nmrxiv-prod
  GKE_ZONE: europe-west3-a
  DEPLOYMENT_NAME: nodejs-nmrxiv-nodejs-microservice
  REPOSITORY_NAME_DEV: nmrxiv-dev
  REPOSITORY_NAME_PROD: nmrxiv-prod
  IMAGE: nmrxiv-nodejs-microservice

jobs:
  build and test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Create .env file'
        run: |
          touch .env
          cp .env.example .env
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  setup-build-publish-deploy-dev:
    name: deploy to dev
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud auth configure-docker europe-west3-docker.pkg.dev
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_DEV }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build Image
        run: |-
          docker build --tag europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME_DEV/$IMAGE:latest .
      # Push the Docker image to Google Artifact Registry
      - name: Publish Image to Google Artifact Registry
        run: |-
          docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME_DEV/$IMAGE:latest"

      # Deploy the latest Docker image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl rollout restart deployment/$DEPLOYMENT_NAME
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
          kubectl get services -o wide

  setup-build-publish-deploy-prod:
    name: deploy to prod
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud auth configure-docker europe-west3-docker.pkg.dev
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.3.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_PROD }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build Image
        run: |-
          docker build --tag europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME_PROD/$IMAGE:latest .
      # Push the Docker image to Google Artifact Registry
      - name: Publish Image to Google Artifact Registry
        run: |-
          docker push "europe-west3-docker.pkg.dev/$PROJECT_ID/$REPOSITORY_NAME_PROD/$IMAGE:latest"

      # Deploy the latest Docker image to the GKE cluster
      - name: Deploy
        run: |-
          kubectl rollout restart deployment/$DEPLOYMENT_NAME
          kubectl rollout status deployment/$DEPLOYMENT_NAME --timeout=300s
          kubectl get services -o wide
