name: e2e tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          node-version: '20' # fallback if not found in package.json
      - name: 'Create .env file'
        run: |
            touch .env
            cp .env.example .env
      - name: Install dependencies
        run: npm ci
      - name: Build test application
        run: npm run build --if-present
      - name: Run test
        run: npm test