# This worklflow will perform following actions when the code is pushed to main branch.
# - Run end to end test
# - Test linting.
# - Trigger release-please action to create release which needs e2etest & lint to pass first.
#
# Maintainers:
#   - name: Nisha Sharma
#   - email: nisha.sharma@uni-jena.de

name: release-please

on:
  push:
    branches:
      - main

jobs:
  e2etest:
    uses: NFDI4Chem/nmrxiv-nodejs-microservice/.github/workflows/e2e.yml@development

  release-please:
    runs-on: ubuntu-latest
    needs: e2etest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.PAT}}
