
# This worklflow will perform following actions when the code is pushed to main branch.
# - Run end to end test
# - Test linting.
# - Trigger release-please action to create release which needs e2etest & lint to pass first.
# 
# Maintainers:
#   - name: Nisha Sharma
#   - email: nisha.sharma@uni-jena.de

name: release-please 

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 'Create .env file'
        run: |
          touch .env
          cp .env.example .env
      - run: npm ci
      - run: npm run build --if-present
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run test
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run eslint
      - name: Run Prettier
        run: npm run prettier
      - name: Check types
        run: npm run check-types

  release-please:
    runs-on: ubuntu-latest
    needs: ['lint', 'test']
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true