# This worklflow will perform following actions when the code is pushed to main branch.
# - Run end to end test
# - Test linting.
# - Trigger release-please action to create release which needs e2etest & lint to pass first.
#
# Maintainers:
#   - name: Nisha Sharma
#   - email: nisha.sharma@uni-jena.de

name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  e2etest:
    uses: NFDI4Chem/nmrxiv-nodejs-microservice/.github/workflows/e2e.yml@development

  release-please:
    runs-on: ubuntu-latest
    needs: e2etest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: nmrxiv-nodejs-microservice
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: main
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{"type":"docs","section":"Documentation","hidden":false},{"type":"ci","section":"CI/CD","hidden":false},{"type":"build","section":"Build","hidden":false},{"type":"refactor","section":"Refactoring","hidden":false}]'
